# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---


- name: Ensure autofs is removed (CIS)
  become: true
  ansible.builtin.package:
    name: autofs
    state: absent
  when:
    - ansible_system == 'Linux'
